name: Node CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    env:
      FORCE_COLOR: '1'
    name: Build & Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: '^20.19.0'
          - node-version: '^22.12.0'
          - node-version: '^24.0.0'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test (Node v20.x)
        if: startsWith(matrix.node-version, '^20')
        # CAUTION: this only works in POSIX environments
        run: npm run test:node20
      - name: Test
        if: ${{ !startsWith(matrix.node-version, '^20') }}
        run: npm test
